apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway-v2
  namespace: rapido-prod

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway
      version: v2

  template:
    metadata:
      labels:
        app: api-gateway
        version: v2

    spec:
      containers:
        - name: api-gateway

          image: rapido-clone-backend-api-gateway:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka"