apiVersion: v1
kind: ConfigMap
metadata:
  name: rapido-config
  namespace: rapido-prod

data:
  POSTGRES_HOST: postgres
  POSTGRES_DB: rapido_db

  REDIS_HOST: redis

  RABBITMQ_HOST: rabbitmq

  EUREKA_SERVER_URL: http://eureka-server:8761/eureka