apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: rapido-prod

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: rapido-clone-backend-notification-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8086

          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/rapido_db"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rapido-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rapido-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_REDIS_HOST
              value: "redis"

            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"

            - name: SPRING_RABBITMQ_PORT
              value: "5672"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: rapido-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: rapido-prod

spec:
  selector:
    app: notification-service

  ports:
    - port: 8086
      targetPort: 8086

  type: ClusterIP