spring.application.name=DRIVER-SERVICE

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/rapido_db
spring.datasource.username=rapido_user
spring.datasource.password=rapido_pass

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

jwt.secret=mySecretKeymySecretKeymySecretKey123456